# Formulas
brew "webp"
brew "python@3.13"
brew "awscli"
brew "bash"
brew "bat"
brew "bat-extras"
brew "coreutils"
brew "e2fsprogs"
brew "fd"
brew "fzf"
brew "gh"
brew "go"
brew "golangci-lint"
brew "node"
brew "pfetch-rs"
brew "php"
brew "pillow"
brew "powerlevel10k"
brew "ripgrep"
brew "shfmt"
brew "sqlfmt"
brew "wget"
brew "yadm"
brew "zoxide"
brew "eza"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"


# Casks
cask "font-terminess-ttf-nerd-font"
cask "vlc"
cask "1password"
cask "alfred"
cask "bettertouchtool"
cask "devutils"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "sidenotes"
cask "slidepad"
cask "zoom"
cask "trex"
cask "tabtab"
cask "qbittorrent"
cask "google-chrome"
cask "dropzone"

# Mac App Store
mas "Things3", id: 904280696
mas "Spark-Classic-Email", id: 1176895641
